### ISSUE TITLE
Notes list crashes

### ISSUE THREAD

**Issue by opk12** [hauke96/GeoNotes#122]
The app crashes when I use the list of notes, with this cause.

```
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
```

For example, these steps sometimes work and sometimes crash.

a. In the hamburger menu, tap the entry for the notes list.
b. Do a; tap the Filter button; tap the Back button twice.
c. Do a; tap the Filter button; type something; tap Ok; tap on a note.

Example trace from a.

```
FATAL EXCEPTION: main
Process: de.hauke_stieler.geonotes, PID: 9244
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.hauke_stieler.geonotes/de.hauke_stieler.geonotes.note_list.NoteListActivity}: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default.
    (unable to open database file (code 2062))
#################################################################
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
    at android.app.ActivityThread.-wrap14(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6816)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default.
    (unable to open database file (code 2062))
#################################################################
    at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:995)
    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
    at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
    at de.hauke_stieler.geonotes.categories.CategoryStore.getCategory(CategoryStore.java:68)
    at de.hauke_stieler.geonotes.notes.NoteStore.getNoteFromCursor(NoteStore.java:176)
    at de.hauke_stieler.geonotes.notes.NoteStore.getAllNotes(NoteStore.java:126)
    at de.hauke_stieler.geonotes.database.Database.getAllNotes(Database.java:91)
    at de.hauke_stieler.geonotes.note_list.NoteListActivity.load(NoteListActivity.java:54)
    at de.hauke_stieler.geonotes.note_list.NoteListActivity.onCreate(NoteListActivity.java:50)
    at android.app.Activity.performCreate(Activity.java:6977)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
    ... 9 more
```

**Additional information**
I am on app version 1.6.0 from F-droid, on Samsung Android 7.1. The phone is low on internal memory, if it matters.

**Comment by hauke96** [comment]
Thanks for the bug report. Unfortunately I'm not able to reproduce the bug and never experienced it or heard of it. However, I'll keep an eye on that and do some research when I find the time for it.
